apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app-ingress
  annotations:
    # NGINX ని రూటింగ్ కోసం వాడమని చెప్తున్నాం
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Socket.io కోసం స్టిక్కీ సెషన్స్
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chat-app-service
            port:
              number: 80
