apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app-ingress
  annotations:
    # Important: NGINX Controller ni use cheyamani chepthunnam
    kubernetes.io/ingress.class: "nginx"
    # Socket.io kosam Sticky Sessions (Affinity)
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chat-app-service
            port:
              number: 80
